#+DATE:    January 14, 2020
#+TITLE:   A Personal Finance Basics Overview

* Table of Contents :TOC_3:noexport:
- [[#minimum-knowledge][Minimum Knowledge]]
- [[#where-to-put-your-money][Where to put your money]]
  - [[#tfsa][TFSA]]
  - [[#rrsp][RRSP]]
    - [[#fthbp][FTHBP]]
- [[#what-to-buy][What to buy]]
  - [[#better][Better]]
  - [[#easiest][Easiest]]
- [[#misc][Misc.]]
  - [[#stocks-bonds-gics-reits][Stocks, Bonds, GICs, REITs]]
  - [[#etf-index-fund][ETF, Index Fund]]
  - [[#dividends][Dividends]]
  - [[#interest][Interest]]
  - [[#capital-gains][Capital Gains]]
- [[#how-to-buy][How to buy]]
  - [[#open-a-questrade-account][open a questrade account]]
    - [[#use-referral-code][use referral code:]]
  - [[#fund-your-account][fund your account]]

* Minimum Knowledge
Make money, keep it (don't spend it on things you don't need), invest it.

* Where to put your money
In Canada, TFSA, and RRSP.

** TFSA
A place to put your money and not pay any tax.

There is a limit on what you can put in, but it increases every year (by the
same amount, regardless of what you make)

**You pay tax 15% tax on dividends from US stocks


** RRSP
A way to get free money right now, and pay the tax when you windraw later.
("free", you get some of the income tax you paid back)

The idea is get the money now so you can invest it, then withdraw once you've reduced
your income to a low tax bracket, or when you buy a home (see FTHBP below).

The more you make, the more you can put in, the more you get back.
To put in the max of $26,500, you need to make around $150k/yr, and you would
get around $11.5k in tax savings ("free money").

You can also roll the taxable income reduction to future years, this can be advantageous
if you will be jumping tax brackets or are planning on having kids soon and want to 
reduce your taxable income enough to get more from the child tax credit. 

#+TBLFM: $1=26500/.18
*** FTHBP
First-time home buyers plan

If you are buying your first home, you can withdraw 35K from your RRSP tax free.
You have to put 35k back into your RRSP within 17 years of taking it out
(starting year 2). You don't get any money back on this since you already did
when you first put it in.

The point of doing this is to get free money for putting 35k into your RRSP.
Then use it for a down payment on your first home.
When it appreciates, you can sell for a tax free profit to use to buy your next place.

Remember you eventually have to pay tax when you take money our of here.
This makes it a good place to keep fixed income portion of your portfolio.



* What to buy
ETFs exchange traded funds.
In Canada
** Better

| Ticker | Allocation |
|--------+------------|
| XAW    |        60% |
| VCN    |        30% |
| ZAG    |        10% |

** Easiest
Just buy VGRO or XGRO


* TODO Misc.
** Stocks, Bonds, GICs, REITs
** ETF, Index Fund
** Dividends
Pay almost less tax on Canadian Dividends. You get a tax credit that partially offsets the tax you pay, this is dependent on your tax bracket and only slightly preferable to receiving the same income on your paycheck.
There are 2 types of dividends, eligible and ineligible.  The company you are getting dividends will say if the dividends are eligible or ineligible.
Eligible dividends, save you more tax and are better.

** Interest
Pay 100% tax, keep interst paying assets in RRSP
** Capital Gains
Pay income tax on 50% of realized gain.
* TODO How to buy
** open a questrade account
You need to deposit a minimum of $1000
*** use referral code:
    =616304821418115=
    You will get: 

    | Free money | When you deposit |
    |------------+------------------|
    | $25        | $1,000 (minimum) |
    | $50        | $10,000          |
    | $75        | $25,000          |
    | $100       | $50,000          |
    | $250       | $100,000         |

    You have 90 days within opening an account to deposit the amount required to reach the next reward level.


** fund your account
1. on your banks website/app go to to ==pay bill=
2. choose =QUESTRADE INC=
3. add =questrade account number= your account number
   You will see your account number on questrade right before the accoutn type
   e.g. 5132938472 - TFSA, or 5142349062 - RRSP
4. "pay the bill" to transfer money
   It will take 1-2 business days, occasionally it takes a bit longer
   Plan ahead and fund your account earlier rather than later, you wont be able to buy when there is a dip if you dont
   already have money in your questrade account
5. repeat for your other questrade account(s)
